#!/bin/bash

DISK="sdb"

PARTITIONS=("15%" "10%" "*" "SWAP" "DATA" "20GB")

$TASKS=("CREATE TABLE" "CREATE PARTITIONS" "RESTORE RECU" "RESTORE DATA" "MOUNT SWAP" "COPY IMAGES" "RESTORE GNU" "RESTORE WIN")