#!/bin/bash

# DISK="sdb"

IDX_WIN=0
IDX_GNU=1
IDX_EXT=2
IDX_SWAP=3
IDX_DATA=4
IDX_RECOVERY=5

PARTITIONS[$IDX_WIN]="15%"
PARTITIONS[$IDX_GNU]="10%"
PARTITIONS[$IDX_EXT]="EXT"
PARTITIONS[$IDX_SWAP]="SWAP"
PARTITIONS[$IDX_DATA]="DATA"
PARTITIONS[$IDX_RECOVERY]="20GB"

TASKS=("CREATE_TABLE" "CREATE_PARTITIONS" "RESTORE_RECU" "RESTORE_DATA" "MOUNT" "COPY_IMG_GNU" "COPY_IMG_WIN" "RESTORE_GNU" "RESTORE_WIN")

IMAGES_SOURCE="/mnt/home/images/"


WIN_IMG_NAME="win-img"
GNU_IMG_NAME="gnu-img"
DATA_IMG_NAME="data-img"
RECOVERY_IMG_NAME="recovery-img"